### ISSUE TITLE
Update steampunk scanner

### ISSUE THREAD

**Issue by RedekG** [xlab-si/iac-scan-runner#56] opened 2023-03-01 08:57 UTC
Steampunk scanner does not work since it changed it's name to Spotter. Rename all variables to the new naming convention.

**Comment by anzoman** [comment] 2023-04-19 07:51
Closing as this is a duplicate of https://github.com/xlab-si/iac-scan-runner/issues/48.

**Closed by anzoman** 2023-04-19 07:51 UTC
Labels: bug
